[package]
name = "aoc2021"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "1"
path = "src/bin/day1.rs"

[[bin]]
name = "2"
path = "src/bin/day2.rs"

[[bin]]
name = "3"
path = "src/bin/day3.rs"

[[bin]]
name = "4"
path = "src/bin/day4.rs"

[[bin]]
name = "5"
path = "src/bin/day5.rs"

[[bin]]
name = "6"
path = "src/bin/day6.rs"

[[bin]]
name = "7"
path = "src/bin/day7.rs"

[[bin]]
name = "8"
path = "src/bin/day8.rs"

[[bin]]
name = "9"
path = "src/bin/day9.rs"
