[package]
name = "aoc2022"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "1"
path = "src/bin/1.rs"

[[bin]]
name = "2"
path = "src/bin/2.rs"

[[bin]]
name = "4"
path = "src/bin/4.rs"
